/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_smile_crystal_JNITest */

#ifndef _Included_com_smile_crystal_JNITest
#define _Included_com_smile_crystal_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testPrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_smile_crystal_JNITest_testPrint
  (JNIEnv *, jobject);

/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_smile_crystal_JNITest_testAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
