/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smile_crystal_JNITest */

#ifndef _Included_com_smile_crystal_JNITest
#define _Included_com_smile_crystal_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testPrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_smile_crystal_JNITest_testPrint
  (JNIEnv *, jobject);

/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_smile_crystal_JNITest_testAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testObject1
 * Signature: (Lcom/smile/crystal/TestStruct;Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_smile_crystal_JNITest_testObject1
  (JNIEnv *, jobject, jobject, jstring, jobject);

/*
 * Class:     com_smile_crystal_JNITest
 * Method:    testReturn
 * Signature: ()Lcom/smile/crystal/TestStruct;
 */
JNIEXPORT jobject JNICALL Java_com_smile_crystal_JNITest_testReturn
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
